# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='login_registration.User'),
        ),
    ]
